repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.*\.ipynb$
      - id: end-of-file-fixer
        exclude: ^.*\.ipynb$
      - id: check-added-large-files
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.5
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        exclude: ^.*\.ipynb$
      # Run the formatter.
      - id: ruff-format
        exclude: ^.*\.ipynb$
